name: "SonarCloud"

on:
  workflow_run:
    workflows: ["Pull Request", "Push"]
    types:
      - completed

jobs:
  sonarcloud-check:
    name: "SonarCloud Check"
    uses: mParticle/mparticle-workflows/.github/workflows/sonarcloud.yml@main
    secrets: inherit
